version: '3.8'

services:
  fhirhub:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # Désactiver la détection des versions de Node.js trop récentes dans le conteneur
      - SKIP_NODE_VERSION_CHECK=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s