version: '3.8'

services:
  # Application principale FHIRHub
  fhirhub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fhirhub
    restart: unless-stopped
    ports:
      - "${PORT:-5000}:5000"
      - "${METRICS_PORT:-9091}:9091"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_PATH=/app/storage/db/fhirhub.db
      - JWT_SECRET=${JWT_SECRET:-fhirhub-secure-jwt-secret}
      - METRICS_ENABLED=${METRICS_ENABLED:-true}
      - METRICS_PORT=${METRICS_PORT:-9091}
    volumes:
      # Utiliser des chemins absolus pour les volumes avec séparation claire
      - ${DB_DIR:-./volumes/db}:/app/storage/db
      - ${DATA_DIR:-./volumes/data}:/app/storage/data
      - ${LOGS_DIR:-./volumes/logs}:/app/storage/logs
      - ${BACKUPS_DIR:-./volumes/backups}:/app/storage/backups
      - ${TERMINOLOGY_DIR:-./volumes/french_terminology}:/app/french_terminology
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - fhirhub-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"

  # Prometheus pour la collecte de métriques (optionnel en production, activé par défaut)
  prometheus:
    image: prom/prometheus:latest
    container_name: fhirhub-prometheus
    restart: unless-stopped
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ${PROMETHEUS_CONFIG:-./prometheus/prometheus.yml}:/etc/prometheus/prometheus.yml
      - ${PROMETHEUS_DATA:-./volumes/prometheus}:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    depends_on:
      - fhirhub
    networks:
      - fhirhub-network
    profiles:
      - monitoring

  # Grafana pour la visualisation des métriques (optionnel en production, activé par défaut)
  grafana:
    image: grafana/grafana:latest
    container_name: fhirhub-grafana
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    volumes:
      - ${GRAFANA_DATA:-./volumes/grafana}:/var/lib/grafana
      - ${GRAFANA_PROVISIONING:-./grafana/provisioning}:/etc/grafana/provisioning
      - ${GRAFANA_DASHBOARDS:-./grafana/dashboards}:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-fhirhub-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    depends_on:
      - prometheus
    networks:
      - fhirhub-network
    profiles:
      - monitoring

# Définition des réseaux
networks:
  fhirhub-network:
    driver: bridge