version: '3.8'

services:
  fhirhub:
    container_name: fhirhub
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5001"
      - "9091:9091"
    volumes:
      - ./data/db:/app/storage/db
      - ./data/app_data:/app/storage/data
      - ./data/logs:/app/storage/logs
      - ./data/backups:/app/storage/backups
      - ./data/french_terminology:/app/french_terminology
    environment:
      - NODE_ENV=production
      - PORT=5001
      - METRICS_PORT=9091
      - METRICS_ENABLED=true
      - DB_PATH=/app/storage/db/fhirhub.db
      - LOG_LEVEL=info
      - MISTRAL_API_KEY=${MISTRAL_API_KEY:-VNjTxMwJ1UwOpQBDERIAwdWKK4LHsCXd}
    restart: unless-stopped
    networks:
      - fhirhub-network

networks:
  fhirhub-network:
    driver: bridge