version: '3.8'

services:
  fhirhub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fhirhub
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_PATH=/app/data/fhirhub.db
      - JWT_SECRET=fhirhub-secure-jwt-secret-for-production
    volumes:
      # Volume pour les données persistantes
      - fhirhub_data:/app/data
      # Volume pour les logs
      - fhirhub_logs:/app/logs
      # Volume pour les sauvegardes
      - fhirhub_backups:/app/backups
      # Volume pour les terminologies françaises
      - fhirhub_terminology:/app/french_terminology

# Définition des volumes persistants
volumes:
  fhirhub_data:
    driver: local
  fhirhub_logs:
    driver: local
  fhirhub_backups:
    driver: local
  fhirhub_terminology:
    driver: local