version: '3.8'

services:
  # Application principale FHIRHub
  fhirhub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fhirhub
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "9091:9091"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_PATH=/app/storage/db/fhirhub.db
      - JWT_SECRET=fhirhub-secure-jwt-secret-for-production
      - METRICS_ENABLED=true
      - METRICS_PORT=9091
    volumes:
      # Volume pour la base de données (séparée)
      - fhirhub_db:/app/storage/db
      # Volume pour les données persistantes (conversions, etc.)
      - fhirhub_data:/app/storage/data
      # Volume pour les logs
      - fhirhub_logs:/app/storage/logs
      # Volume pour les sauvegardes
      - fhirhub_backups:/app/storage/backups
      # Volume pour les terminologies françaises
      - fhirhub_terminology:/app/french_terminology
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - fhirhub-network

  # Prometheus pour la collecte de métriques
  prometheus:
    image: prom/prometheus:latest
    container_name: fhirhub-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    depends_on:
      - fhirhub
    networks:
      - fhirhub-network

  # Grafana pour la visualisation des métriques
  grafana:
    image: grafana/grafana:latest
    container_name: fhirhub-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=fhirhub-admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    depends_on:
      - prometheus
    networks:
      - fhirhub-network

# Définition des volumes persistants
volumes:
  fhirhub_db:
    driver: local
  fhirhub_data:
    driver: local
  fhirhub_logs:
    driver: local
  fhirhub_backups:
    driver: local
  fhirhub_terminology:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

# Définition des réseaux
networks:
  fhirhub-network:
    driver: bridge