version: '3.8'

# Utilisation de volumes nommés pour isoler complètement les données
volumes:
  fhirhub_db_minimal:
    name: fhirhub_db_minimal
  fhirhub_data_minimal:
    name: fhirhub_data_minimal
  fhirhub_logs_minimal:
    name: fhirhub_logs_minimal
  fhirhub_backups_minimal:
    name: fhirhub_backups_minimal
  fhirhub_terminology_minimal:
    name: fhirhub_terminology_minimal

services:
  fhirhub:
    container_name: fhirhub-minimal
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"  # Utilisation du port 5001 pour éviter les conflits
      - "9091:9091"
    volumes:
      # Utilisation de volumes nommés pour une meilleure isolation et portabilité
      - fhirhub_db_minimal:/app/storage/db:rw
      - fhirhub_data_minimal:/app/storage/data:rw
      - fhirhub_logs_minimal:/app/storage/logs:rw
      - fhirhub_backups_minimal:/app/storage/backups:rw
      - fhirhub_terminology_minimal:/app/french_terminology:rw
      # Dossiers mappés pour faciliter l'import/export de données
      - ./import:/app/import:ro
      - ./export:/app/export:rw
    environment:
      - NODE_ENV=production
      - PORT=5001  # Utilisation du port 5001 pour éviter les conflits
      - METRICS_PORT=9091
      - METRICS_ENABLED=true
      - DB_PATH=/app/storage/db/fhirhub.db
      - DB_PERSISTENT=true
      - JWT_SECRET=fhirhub-secure-jwt-secret
      - LOG_LEVEL=info
      - MISTRAL_API_KEY=${MISTRAL_API_KEY:-VNjTxMwJ1UwOpQBDERIAwdWKK4LHsCXd}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - fhirhub-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

networks:
  fhirhub-network:
    driver: bridge