version: '3.8'

services:
  # Application principale FHIRHub
  fhirhub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fhirhub
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "9091:9091"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_PATH=/app/storage/db/fhirhub.db
      - JWT_SECRET=fhirhub-secure-jwt-secret
      - METRICS_ENABLED=true
      - METRICS_PORT=9091
    volumes:
      # Volume pour la base de données
      - ./volumes/db:/app/storage/db
      # Volume pour les données persistantes
      - ./volumes/data:/app/storage/data
      # Volume pour les logs
      - ./volumes/logs:/app/storage/logs
      # Volume pour les sauvegardes
      - ./volumes/backups:/app/storage/backups
      # Volume pour les terminologies françaises
      - ./volumes/french_terminology:/app/french_terminology
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - fhirhub-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"

  # Prometheus pour la collecte de métriques
  prometheus:
    image: prom/prometheus:latest
    container_name: fhirhub-prometheus
    restart: unless-stopped
    ports:
      - "9092:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./volumes/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--no-scrape.adjust-timestamps'
    user: "1000:1000"
    depends_on:
      - fhirhub
    networks:
      - fhirhub-network
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  # Grafana pour la visualisation des métriques
  grafana:
    image: grafana/grafana:latest
    container_name: fhirhub-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./volumes/grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=fhirhub-admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_LOGS=/var/lib/grafana/logs
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
    user: "1000:1000" 
    depends_on:
      - prometheus
    networks:
      - fhirhub-network
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  # Node Exporter pour la collecte de métriques système
  node-exporter:
    image: prom/node-exporter:latest
    container_name: fhirhub-node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - fhirhub-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Définition des réseaux
networks:
  fhirhub-network:
    driver: bridge