[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fhirclient>=4.3.1",
    "hl7>=0.4.5",
    "hl7apy>=1.3.5",
    "requests>=2.32.3",
    "trafilatura>=2.0.0",
]
